# Copyright (c) 2022-2024, Keivan Tafakkori. All rights reserved.
# See the file LICENSE file for licensing details.

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Output formats
formats:
  - pdf
  - epub

python:
  # Installation requirements
  install:
    - requirements: docs/requirements.txt