version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py

# Output formats
formats:
  - pdf
  - epub

python:
  # Installation requirements
  install:
    - requirements: docs/requirements.txt