# https://www.mkdocs.org/user-guide/configuration/

site_name: FelooPy user guide
site_url: https://feloopy.readthedocs.io/en/latest/
repo_url: https://github.com/ktafakkori/feloopy
repo_name: ktafakkori/feloopy

theme:

  name: material
  #custom_dir: docs/_build/overrides
  palette:

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  logo: _build/assets/logo.png
  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
  icon:
    repo: fontawesome/brands/github

extra_css:
  - _build/css/extra.css

# Preview controls
strict: true

# Formatting options
markdown_extensions:
  - admonition
  - pymdownx.details
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: ['.','docs/src/']
      check_paths: true
  - footnotes

plugins:
  - search:
      lang: en