# https://www.mkdocs.org/user-guide/configuration/

site_name: FelooPy user guide
site_url: https://feloopy.readthedocs.io/en/latest/
repo_url: https://github.com/ktafakkori/feloopy
repo_name: ktafakkori/feloopy

nav:
  - User guide:
    - index.md
    - Getting started: user-guide/getting-started.md
    - Installation: user-guide/installation.md
    - Concepts:
      - concepts/index.md
      - Environments: concepts/environments.md
      - Sets: concepts/sets.md
      - Parameters: concepts/parameters.md
      - Variables: concepts/variables.md
      - Constraints: concepts/constraints.md
      - Objectives: concepts/objectives.md
      - Facilitators: concepts/facilitators.md
      - Handlers: concepts/handlers.md
      - Configurators: concepts/configurators.md
      - Analyzers: concepts/analyzers.md
  
  - About: about/index.md

theme:

  name: material
  font: false
  palette:

  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    primary: black
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    primary: black
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
  
  logo: assets/logo.png
  favicon: assets/favicon.png

  features:
    - navigation.tracking
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.footer
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - content.code.annotate

  icon:
    repo: fontawesome/brands/github

# Preview controls
strict: true

# Formatting options
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.arithmatex
  - pymdownx.mark
  - pymdownx.smartsymbols
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.snippets:
      base_path: ['.','docs/inputs/','docs/outputs/']
  - footnotes

plugins:
  - search:
      lang: en
  - macros
  - markdown-exec
  - material-plausible

extra_css:
  - stylesheets/better.css
  - https://fonts.cdnfonts.com/css/noto-serif
  - https://fonts.cdnfonts.com/css/noto-mono


extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
  
copyright: Copyright &copy; 2022 - 2024 Keivan Tafakkori

extra:

  social:
    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/in/keivan-tafakkori/
    - icon: fontawesome/brands/discord
      link: https://discord.gg/VpZDeG8wbv
    - icon: fontawesome/brands/github
      link: https://github.com/ktafakkori
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/ktafakkori
    - icon: fontawesome/solid/paper-plane
      link: mailto:feloop.crm@gmail.com

