from .feloopy import *
from .operators import *

from .feloopy import *
from .operators import *

heuristic_algorithms = ['original_ep',
                        'levy_ep',
                        'original_es',
                        'levy_es',
                        'original_ma',
                        'base_ga',
                        'single_ga',
                        'multi_ga',
                        'elite_single_ga',
                        'elite_multi_ga',
                        'base_de',
                        'ja_de',
                        'sa_de',
                        'sha_de',
                        'l_sha_de',
                        'sap_de',
                        'original_fpa',
                        'original_cro',
                        'o_cro',
                        'original_pso',
                        'p_pso',
                        'h_pso_tvac',
                        'c_pso',
                        'cl_pso',
                        'original_bfo',
                        'a_bfo',
                        'original_beesa',
                        'prob_beesa',
                        'original_cso',
                        'original_abc',
                        'original_acor',
                        'original_csa',
                        'original_ffa',
                        'original_fa',
                        'original_ba',
                        'adaptive_ba',
                        'modified_ba',
                        'original_foa',
                        'base_foa',
                        'whale_foa',
                        'original_sspidero',
                        'original_gwo',
                        'rw_gwo',
                        'original_sspidera',
                        'original_alo',
                        'base_alo',
                        'original_mfo',
                        'base_mfo',
                        'original_eho',
                        'original_ja',
                        'base_ja',
                        'levy_ja',
                        'original_woa',
                        'hi_woa',
                        'original_do',
                        'original_bsa',
                        'original_sho',
                        'original_sso',
                        'original_srsr',
                        'original_goa',
                        'original_coa',
                        'original_msa',
                        'original_slo',
                        'modified_slo',
                        'improved_slo',
                        'original_nmra',
                        'improved_nmra',
                        'original_pfa',
                        'original_sfo',
                        'improved_sfo',
                        'original_hho',
                        'original_mrfo',
                        'original_bes',
                        'original_ssa',
                        'base_ssa',
                        'original_hgs',
                        'original_ao',
                        'gwo_woa',
                        'original_mpa',
                        'original_hba',
                        'original_scso',
                        'original_tso',
                        'original_avoa',
                        'original_agto',
                        'original_aro',
                        'original_sa',
                        'original_wdo',
                        'original_mvo',
                        'base_mvo',
                        'original_two',
                        'oppo_two',
                        'levy_two',
                        'enhanced_two',
                        'original_efo',
                        'base_efo',
                        'original_nro',
                        'original_hgso',
                        'original_aso',
                        'original_eo',
                        'modified_eo',
                        'adaptive_eo',
                        'original_archoa',
                        'original_ca',
                        'original_ica',
                        'original_tlo',
                        'base_tlo',
                        'i_tlo',
                        'original_bso',
                        'improved_bso',
                        'original_qsa',
                        'base_qsa',
                        'oppo_qsa',
                        'levy_qsa',
                        'improved_qsa',
                        'original_saro',
                        'base_saro',
                        'original_lco',
                        'base_lco',
                        'improved_lco',
                        'original_ssdo',
                        'original_gska',
                        'base_gska',
                        'original_chio',
                        'base_chio',
                        'original_fbio',
                        'base_fbio',
                        'original_bro',
                        'base_bro',
                        'original_spbo',
                        'devspbo',
                        'original_dmoa',
                        'devdmoa',
                        'original_iwo',
                        'original_bbo',
                        'base_bbo',
                        'original_vcs',
                        'base_vcs',
                        'original_sbo',
                        'base_sbo',
                        'original_eoa',
                        'original_who',
                        'original_sma',
                        'base_sma',
                        'original_bmo',
                        'original_tsa',
                        'original_sos',
                        'original_soa',
                        'dev_soa',
                        'original_gco',
                        'base_gco',
                        'original_wca',
                        'original_aeo',
                        'enhanced_aeo',
                        'modified_aeo',
                        'improved_aeo',
                        'adaptive_aeo',
                        'original_hc',
                        'swarm_hc',
                        'original_cem',
                        'original_sca',
                        'base_sca',
                        'original_gbo',
                        'orginal_aoa',
                        'original_cgo',
                        'original_pss',
                        'original_info',
                        'original_run',
                        'original_circle_sa',
                        'original_hs',
                        'base_hs'
                        ]

exact_algorithms = [

    # gekko
    ['gekko', 'apopt'],
    ['gekko', 'bpopt'],
    ['gekko', 'ipopt'],

    # ortools
    ['ortools', 'bop'],
    ['ortools', 'cbc'],
    ['ortools', 'clp'],
    ['ortools', 'cplex_'],
    ['ortools', 'cplex'],
    ['ortools', 'glop'],
    ['ortools', 'glpk_'],
    ['ortools', 'glpk'],
    ['ortools', 'gurobi_'],
    ['ortools', 'gurobi'],
    ['ortools', 'sat'],
    ['ortools', 'scip'],
    ['ortools', 'xpress_'],
    ['ortools', 'xpress'],

    # pulp
    ['pulp', 'cbc'],
    ['pulp', 'choco'],
    ['pulp', 'coin'],
    ['pulp', 'coinmp_dll'],
    ['pulp', 'cplex_py'],
    ['pulp', 'cplex'],
    ['pulp', 'glpk'],
    ['pulp', 'gurobi_cmd'],
    ['pulp', 'gurobi'],
    ['pulp', 'highs'],
    ['pulp', 'mipcl'],
    ['pulp', 'mosek'],
    ['pulp', 'pyglpk'],
    ['pulp', 'scip'],
    ['pulp', 'xpress_py'],
    ['pulp', 'xpress'],

    # cvxpy
    ['cvxpy', 'osqp'],
    ['cvxpy', 'ecos'],
    ['cvxpy', 'cvxopt'],
    ['cvxpy', 'scs'],
    ['cvxpy', 'scipy'],
    ['cvxpy', 'glop'],
    ['cvxpy', 'glpk'],
    ['cvxpy', 'glpk_mi'],
    ['cvxpy', 'gurobi'],
    ['cvxpy', 'mosek'],
    ['cvxpy', 'cbc'],
    ['cvxpy', 'cplex'],
    ['cvxpy', 'nag'],
    ['cvxpy', 'pdlp'],
    ['cvxpy', 'scip'],
    ['cvxpy', 'xpress'],
    ['cvxpy', 'copt'],
    ['cvxpy', 'clarabel'],
    ['cvxpy', 'proxqp'],

    # cylp
    ['cylp', 'cbc'],

    # gurobi
    ['gurobi', 'gurobi'],

    # cplex
    ['cplex', 'cplex'],

    # linopy
    ['linopy', 'cbc'],
    ['linopy', 'glpk'],
    ['linopy', 'highs'],
    ['linopy', 'gurobi'],
    ['linopy', 'xpress'],
    ['linopy', 'cplex'],

    # mip
    ['mip', 'cbc'],

    # picos
    ['picos', 'cplex'],
    ['picos', 'cvxopt'],
    ['picos', 'ecos'],
    ['picos', 'glpk'],
    ['picos', 'gurobi'],
    ['picos', 'mosek'],
    ['picos', 'mskfn'],
    ['picos', 'osqp'],
    ['picos', 'scip'],
    ['picos', 'smcp'],

    # pymprog
    ['pymprog', 'glpk'],

    # pyomo
    ['pyomo', 'baron'],
    ['pyomo', 'cbc'],
    ['pyomo', 'conopt'],
    ['pyomo', 'cplex'],
    ['pyomo', 'cplex_direct'],
    ['pyomo', 'cplex_persistent'],
    ['pyomo', 'cyipopt'],
    ['pyomo', 'gams'],
    ['pyomo', 'highs'],
    ['pyomo', 'asl'],
    ['pyomo', 'gdpopt'],
    ['pyomo', 'gdpopt.gloa'],
    ['pyomo', 'gdpopt.lbb'],
    ['pyomo', 'gdpopt.loa'],
    ['pyomo', 'gdpopt.ric'],
    ['pyomo', 'glpk'],
    ['pyomo', 'gurobi'],
    ['pyomo', 'gurobi_direct'],
    ['pyomo', 'gurobi_persistent'],
    ['pyomo', 'ipopt'],
    ['pyomo', 'mindtpy'],
    ['pyomo', 'mosek'],
    ['pyomo', 'mosek_direct'],
    ['pyomo', 'mosek_persistent'],
    ['pyomo', 'mpec_minlp'],
    ['pyomo', 'mpec_nlp'],
    ['pyomo', 'multistart'],
    ['pyomo', 'path'],
    ['pyomo', 'scip'],
    ['pyomo', 'trustregion'],
    ['pyomo', 'xpress'],
    ['pyomo', 'xpress_direct'],
    ['pyomo', 'xpress_persistent'],

    # xpress
    ['xpress', 'xpress'],
]

constraint_algorithms = [

    ['cplex_cp', 'cplex'],
    ['ortools_cp', 'ortools']

]

feloopy_heuristic_algorithms = [
    'ga',
    'sa',
    'ts',
    'de',
    'gwo'
]