'''
 # @ Author: Keivan
 # @ Created: 2023-05-11
 # @ Modified: 2023-05-11
 # @ Contact: https://www.linkedin.com/in/keivan-tafakkori/
 # @ Github: https://github.com/ktafakkori
 # @ Website: https://ktafakkori.github.io/
 # @ Copyright: 2023. MIT License. All Rights Reserved.
 '''


from .feloopy import *
from .operators import *

heuristic_algorithms = ['orig_ep',
                        'levy_ep',
                        'orig_es',
                        'levy_es',
                        'orig_ma',
                        'base_ga',
                        'single_ga',
                        'multi_ga',
                        'elite_single_ga',
                        'elite_multi_ga',
                        'base_de',
                        'ja_de',
                        'sa_de',
                        'sha_de',
                        'l_sha_de',
                        'sap_de',
                        'orig_fpa',
                        'orig_cro',
                        'o_cro',
                        'orig_pso',
                        'p_pso',
                        'h_pso_tvac',
                        'c_pso',
                        'cl_pso',
                        'orig_bfo',
                        'a_bfo',
                        'orig_beesa',
                        'prob_beesa',
                        'orig_cso',
                        'orig_abc',
                        'orig_acor',
                        'orig_csa',
                        'orig_ffa',
                        'orig_fa',
                        'orig_ba',
                        'adap_ba',
                        'modi_ba',
                        'orig_foa',
                        'base_foa',
                        'whale_foa',
                        'orig_sspidero',
                        'orig_gwo',
                        'rw_gwo',
                        'orig_sspidera',
                        'orig_alo',
                        'base_alo',
                        'orig_mfo',
                        'base_mfo',
                        'orig_eho',
                        'orig_ja',
                        'base_ja',
                        'levy_ja',
                        'orig_woa',
                        'hi_woa',
                        'orig_do',
                        'orig_bsa',
                        'orig_sho',
                        'orig_sso',
                        'orig_srsr',
                        'orig_goa',
                        'orig_coa',
                        'orig_msa',
                        'orig_slo',
                        'modi_slo',
                        'impr_slo',
                        'orig_nmra',
                        'impr_nmra',
                        'orig_pfa',
                        'orig_sfo',
                        'impr_sfo',
                        'orig_hho',
                        'orig_mrfo',
                        'orig_bes',
                        'orig_ssa',
                        'base_ssa',
                        'orig_hgs',
                        'orig_ao',
                        'gwo_woa',
                        'orig_mpa',
                        'orig_hba',
                        'orig_scso',
                        'orig_tso',
                        'orig_avoa',
                        'orig_agto',
                        'orig_aro',
                        'orig_sa',
                        'orig_wdo',
                        'orig_mvo',
                        'base_mvo',
                        'orig_two',
                        'oppo_two',
                        'levy_two',
                        'enha_two',
                        'orig_efo',
                        'base_efo',
                        'orig_nro',
                        'orig_hgso',
                        'orig_aso',
                        'orig_eo',
                        'modi_eo',
                        'adap_eo',
                        'orig_archoa',
                        'orig_ca',
                        'orig_ica',
                        'orig_tlo',
                        'base_tlo',
                        'i_tlo',
                        'orig_bso',
                        'impr_bso',
                        'orig_qsa',
                        'base_qsa',
                        'oppo_qsa',
                        'levy_qsa',
                        'impr_qsa',
                        'orig_saro',
                        'base_saro',
                        'orig_lco',
                        'base_lco',
                        'impr_lco',
                        'orig_ssdo',
                        'orig_gska',
                        'base_gska',
                        'orig_chio',
                        'base_chio',
                        'orig_fbio',
                        'base_fbio',
                        'orig_bro',
                        'base_bro',
                        'orig_spbo',
                        'dev_spbo',
                        'orig_dmoa',
                        'dev_dmoa',
                        'orig_iwo',
                        'orig_bbo',
                        'base_bbo',
                        'orig_vcs',
                        'base_vcs',
                        'orig_sbo',
                        'base_sbo',
                        'orig_eoa',
                        'orig_who',
                        'orig_sma',
                        'base_sma',
                        'orig_bmo',
                        'orig_tsa',
                        'orig_sos',
                        'orig_soa',
                        'dev_soa',
                        'orig_gco',
                        'base_gco',
                        'orig_wca',
                        'orig_aeo',
                        'enha_aeo',
                        'modi_aeo',
                        'impr_aeo',
                        'adap_aeo',
                        'orig_hc',
                        'swarm_hc',
                        'orig_cem',
                        'orig_sca',
                        'base_sca',
                        'orig_gbo',
                        'orig_aoa',
                        'orig_cgo',
                        'orig_pss',
                        'orig_info',
                        'orig_run',
                        'orig_circ_sa',
                        'orig_hs',
                        'base_hs'
                        ]

exact_algorithms = [

    # gekko
    ['gekko', 'apopt'],
    ['gekko', 'bpopt'],
    ['gekko', 'ipopt'],

    # ortools
    ['ortools', 'bop'],
    ['ortools', 'cbc'],
    ['ortools', 'clp'],
    ['ortools', 'cplex_'],
    ['ortools', 'cplex'],
    ['ortools', 'glop'],
    ['ortools', 'glpk_'],
    ['ortools', 'glpk'],
    ['ortools', 'gurobi_'],
    ['ortools', 'gurobi'],
    ['ortools', 'sat'],
    ['ortools', 'scip'],
    ['ortools', 'xpress_'],
    ['ortools', 'xpress'],

    # pulp
    ['pulp', 'cbc'],
    ['pulp', 'choco'],
    ['pulp', 'coin'],
    ['pulp', 'coinmp_dll'],
    ['pulp', 'cplex_py'],
    ['pulp', 'cplex'],
    ['pulp', 'glpk'],
    ['pulp', 'gurobi_cmd'],
    ['pulp', 'gurobi'],
    ['pulp', 'highs'],
    ['pulp', 'mipcl'],
    ['pulp', 'mosek'],
    ['pulp', 'pyglpk'],
    ['pulp', 'scip'],
    ['pulp', 'xpress_py'],
    ['pulp', 'xpress'],

    # cvxpy
    ['cvxpy', 'osqp'],
    ['cvxpy', 'ecos'],
    ['cvxpy', 'cvxopt'],
    ['cvxpy', 'scs'],
    ['cvxpy', 'scipy'],
    ['cvxpy', 'glop'],
    ['cvxpy', 'glpk'],
    ['cvxpy', 'glpk_mi'],
    ['cvxpy', 'gurobi'],
    ['cvxpy', 'mosek'],
    ['cvxpy', 'cbc'],
    ['cvxpy', 'cplex'],
    ['cvxpy', 'nag'],
    ['cvxpy', 'pdlp'],
    ['cvxpy', 'scip'],
    ['cvxpy', 'xpress'],
    ['cvxpy', 'copt'],
    ['cvxpy', 'clarabel'],
    ['cvxpy', 'proxqp'],

    # cylp
    ['cylp', 'cbc'],

    # gurobi
    ['gurobi', 'gurobi'],

    # cplex
    ['cplex', 'cplex'],

    # linopy
    ['linopy', 'cbc'],
    ['linopy', 'glpk'],
    ['linopy', 'highs'],
    ['linopy', 'gurobi'],
    ['linopy', 'xpress'],
    ['linopy', 'cplex'],

    # mip
    ['mip', 'cbc'],

    # picos
    ['picos', 'cplex'],
    ['picos', 'cvxopt'],
    ['picos', 'ecos'],
    ['picos', 'glpk'],
    ['picos', 'gurobi'],
    ['picos', 'mosek'],
    ['picos', 'mskfn'],
    ['picos', 'osqp'],
    ['picos', 'scip'],
    ['picos', 'smcp'],

    # pymprog
    ['pymprog', 'glpk'],

    # pyomo
    ['pyomo', 'baron'],
    ['pyomo', 'cbc'],
    ['pyomo', 'conopt'],
    ['pyomo', 'cplex'],
    ['pyomo', 'cplex_direct'],
    ['pyomo', 'cplex_persistent'],
    ['pyomo', 'cyipopt'],
    ['pyomo', 'gams'],
    ['pyomo', 'highs'],
    ['pyomo', 'asl'],
    ['pyomo', 'gdpopt'],
    ['pyomo', 'gdpopt.gloa'],
    ['pyomo', 'gdpopt.lbb'],
    ['pyomo', 'gdpopt.loa'],
    ['pyomo', 'gdpopt.ric'],
    ['pyomo', 'glpk'],
    ['pyomo', 'gurobi'],
    ['pyomo', 'gurobi_direct'],
    ['pyomo', 'gurobi_persistent'],
    ['pyomo', 'ipopt'],
    ['pyomo', 'mindtpy'],
    ['pyomo', 'mosek'],
    ['pyomo', 'mosek_direct'],
    ['pyomo', 'mosek_persistent'],
    ['pyomo', 'mpec_minlp'],
    ['pyomo', 'mpec_nlp'],
    ['pyomo', 'multistart'],
    ['pyomo', 'path'],
    ['pyomo', 'scip'],
    ['pyomo', 'trustregion'],
    ['pyomo', 'xpress'],
    ['pyomo', 'xpress_direct'],
    ['pyomo', 'xpress_persistent'],

    # xpress
    ['xpress', 'xpress'],
]

constraint_algorithms = [

    ['cplex_cp', 'cplex'],
    ['ortools_cp', 'ortools']

]

feloopy_heuristic_algorithms = [
    'ga',
    'sa',
    'ts',
    'de',
    'gwo'
]
